development:
  adapter: postgresql
  encoding: unicode
  database: hw_development
  pool: 5
  host: db
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: hw_test
  host: db
  pool: 5
  username: postgres
  password: password
